export type Category = "game" | "film"

export type FontUsage = {
  name: string
  role: string
  foundry?: string
  year?: number
  notes: string
  cssFamily?: string
  googleFont?: string
  sampleText: string
}

export type Work = {
  id: number
  title: string
  titleEn: string
  category: Category
  genres: string[]
  year: number
  developer: string
  image: string
  imageAlt: string
  accentColor: string
  fonts: FontUsage[]
  description: string
}

export const WORKS: Work[] = [
  {
    id: 1,
    title: "赛博朋克 2077",
    titleEn: "Cyberpunk 2077",
    category: "game",
    genres: ["角色扮演", "开放世界", "科幻"],
    year: 2020,
    developer: "CD Projekt Red",
    image: "https://images.unsplash.com/photo-1672872476232-da16b45c9001?w=600&h=800&fit=crop&auto=format",
    imageAlt: "霓虹灯城市夜景",
    accentColor: "#ffdd00",
    description: "夜之城的字体设计集成了朋克美学与工业感，霓虹标牌与终端界面并存，形成独特的视觉语言。",
    fonts: [
      {
        name: "Rajdhani",
        role: "主UI字体",
        foundry: "Google Fonts",
        year: 2014,
        notes: "贯穿整个HUD界面，锐利的笔画呼应赛博朋克的机械美学，是游戏视觉语言的核心。",
        cssFamily: "'Rajdhani', sans-serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;600;700&display=swap",
        sampleText: "NIGHT CITY 2077",
      },
      {
        name: "Orbitron",
        role: "标题字体",
        foundry: "Google Fonts",
        year: 2009,
        notes: "用于游戏主标题及菜单标题，几何化的构型传达科技感与疏离感。",
        cssFamily: "'Orbitron', sans-serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Orbitron:wght@700;900&display=swap",
        sampleText: "CYBERPUNK",
      },
    ],
  },
  {
    id: 2,
    title: "只狼：影逝二度",
    titleEn: "Sekiro: Shadows Die Twice",
    category: "game",
    genres: ["动作", "忍者", "魂系"],
    year: 2019,
    developer: "FromSoftware",
    image: "https://images.unsplash.com/photo-1771893351803-f1d244961c76?w=600&h=800&fit=crop&auto=format",
    imageAlt: "朱红鸟居雾中",
    accentColor: "#cc2200",
    description: "以战国日本为背景，字体选择强调书道传统与刀锋锐意。日文汉字与英文字体的融合考究而克制。",
    fonts: [
      {
        name: "游明朝 / Yu Mincho",
        role: "日文正文字体",
        foundry: "字游工房",
        year: 2012,
        notes: "日版使用游明朝作为主要衬线字体，笔锋收笔模拟毛笔质感，与武士题材高度契合。",
        cssFamily: "'Yu Mincho', 'YuMincho', serif",
        sampleText: "死は恥ではない",
      },
      {
        name: "Cinzel",
        role: "英文标题字体",
        foundry: "Google Fonts",
        year: 2011,
        notes: "英文版标题采用罗马大写刻字风格，传递古典与庄严感，呼应游戏的历史厚重感。",
        cssFamily: "'Cinzel', serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap",
        sampleText: "SHADOWS DIE TWICE",
      },
    ],
  },
  {
    id: 3,
    title: "艾尔登法环",
    titleEn: "Elden Ring",
    category: "game",
    genres: ["动作RPG", "开放世界", "黑暗奇幻"],
    year: 2022,
    developer: "FromSoftware",
    image: "https://images.unsplash.com/photo-1609184767751-61157feb09a4?w=600&h=800&fit=crop&auto=format",
    imageAlt: "山顶城堡",
    accentColor: "#c9a227",
    description: "乔治·马丁参与世界观构建，字体设计需同时承载史诗奇幻的恢宏与黑暗破碎的末世感。",
    fonts: [
      {
        name: "Cinzel Decorative",
        role: "主标题字体",
        foundry: "Google Fonts",
        year: 2011,
        notes: "全大写罗马装饰风格，金色渲染后形成类古代铭文质感，与黄金律的世界观相辅相成。",
        cssFamily: "'Cinzel Decorative', serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700&display=swap",
        sampleText: "ELDEN RING",
      },
      {
        name: "IM Fell English",
        role: "剧情文本字体",
        foundry: "Google Fonts / Igino Marini",
        year: 2009,
        notes: "物品说明与剧情文字采用具有17世纪印刷质感的衬线字体，油墨不均的细节强化了世界的古老感。",
        cssFamily: "'IM Fell English', serif",
        googleFont: "https://fonts.googleapis.com/css2?family=IM+Fell+English:ital@0;1&display=swap",
        sampleText: "A fragment of the Elden Ring...",
      },
    ],
  },
  {
    id: 4,
    title: "明日方舟",
    titleEn: "Arknights",
    category: "game",
    genres: ["塔防", "角色扮演", "科幻"],
    year: 2019,
    developer: "鹰角网络",
    image: "https://images.unsplash.com/photo-1654009603731-20b6d7536002?w=600&h=800&fit=crop&auto=format",
    imageAlt: "机器人站立水中",
    accentColor: "#4a9eff",
    description: "末日科幻世界观中，字体体系兼顾中英双语设计，UI系统字体选择强调精密感与信息层次。",
    fonts: [
      {
        name: "思源黑体 / Source Han Sans",
        role: "中文UI主字体",
        foundry: "Adobe & Google",
        year: 2014,
        notes: "跨平台中文UI标准字体，字重丰富，在小尺寸下仍保持优秀可读性，是国产游戏UI的主流选择。",
        cssFamily: "'Noto Sans SC', sans-serif",
        sampleText: "罗德岛作战指挥",
      },
      {
        name: "Barlow Condensed",
        role: "英文标签字体",
        foundry: "Google Fonts",
        year: 2017,
        notes: "收窄比例的无衬线字体用于英文标签与数值显示，在密集UI中高效传达信息层次。",
        cssFamily: "'Barlow Condensed', sans-serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600;700&display=swap",
        sampleText: "OPERATOR LEVEL 90",
      },
    ],
  },
  {
    id: 5,
    title: "寂静岭 2",
    titleEn: "Silent Hill 2",
    category: "game",
    genres: ["恐怖", "心理", "生存"],
    year: 2001,
    developer: "Konami",
    image: "https://images.unsplash.com/photo-1728755833852-2c138c84cfb1?w=600&h=800&fit=crop&auto=format",
    imageAlt: "黑暗隧道人影",
    accentColor: "#8b6b4a",
    description: "心理恐怖的圣典之作，字体设计回避了任何装饰性，以近乎缺席的视觉处理强化孤立感与不安。",
    fonts: [
      {
        name: "Special Elite",
        role: "文件与信件字体",
        foundry: "Google Fonts",
        year: 2011,
        notes: "游戏内拾取的信件和便条使用磨损打字机字体，不均匀的笔画增添真实的恐怖氛围。",
        cssFamily: "'Special Elite', cursive",
        googleFont: "https://fonts.googleapis.com/css2?family=Special+Elite&display=swap",
        sampleText: "In my restless dreams...",
      },
      {
        name: "Arial Narrow",
        role: "UI系统字体",
        foundry: "Monotype",
        year: 1982,
        notes: "菜单界面刻意使用平庸的系统字体，这种反设计的选择本身就是一种心理叙事手段。",
        cssFamily: "'Arial Narrow', Arial, sans-serif",
        sampleText: "Examine / Take / Leave",
      },
    ],
  },
  {
    id: 6,
    title: "GRIS",
    titleEn: "GRIS",
    category: "game",
    genres: ["平台解谜", "艺术", "独立"],
    year: 2018,
    developer: "Nomada Studio",
    image: "https://images.unsplash.com/photo-1741038273223-69c0ed47bf56?w=600&h=800&fit=crop&auto=format",
    imageAlt: "水彩废墟绿意",
    accentColor: "#7ec8c8",
    description: "水彩画风的纯视觉叙事游戏，几乎不使用文字，字体的稀少本身就是设计语言的一部分。",
    fonts: [
      {
        name: "Libre Baskerville",
        role: "少量UI文本",
        foundry: "Google Fonts / Impallari Type",
        year: 2012,
        notes: "极简主义的字体运用，优雅的衬线字体与水彩风格画面产生温柔的呼应，不抢夺视觉注意力。",
        cssFamily: "'Libre Baskerville', serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&display=swap",
        sampleText: "Grief, in four acts.",
      },
    ],
  },
  {
    id: 7,
    title: "原神",
    titleEn: "Genshin Impact",
    category: "game",
    genres: ["动作RPG", "开放世界", "奇幻"],
    year: 2020,
    developer: "miHoYo",
    image: "https://images.unsplash.com/photo-1742738652590-e9b81249dcf4?w=600&h=800&fit=crop&auto=format",
    imageAlt: "梦幻奇境地貌",
    accentColor: "#5a7fe8",
    description: "提瓦特大陆的多语言字体系统极为复杂，为每个国家/地区设计了专属的文字风格，构建了完整的语言生态。",
    fonts: [
      {
        name: "汉仪旗黑 / HYQiHei",
        role: "中文正文字体",
        foundry: "汉仪字库",
        year: 2010,
        notes: "商业授权的专业中文字体，字形精美、字重层次丰富，是国产顶级游戏中文UI的标杆选择。",
        cssFamily: "'Noto Sans SC', sans-serif",
        sampleText: "旅行者，你好",
      },
      {
        name: "HYWenHei",
        role: "标题与强调",
        foundry: "汉仪字库",
        notes: "文黑系列兼具黑体的现代感与明体的传统气韵，用于章节标题和重要剧情节点的强调文本。",
        cssFamily: "'Noto Serif SC', serif",
        sampleText: "神之眼",
      },
    ],
  },
  {
    id: 8,
    title: "黑神话：悟空",
    titleEn: "Black Myth: Wukong",
    category: "game",
    genres: ["动作RPG", "神话", "国产"],
    year: 2024,
    developer: "游戏科学",
    image: "https://images.unsplash.com/photo-1760096231382-6310e8888a94?w=600&h=800&fit=crop&auto=format",
    imageAlt: "迷雾森林人影",
    accentColor: "#336BF4",
    description: "基于《西游记》的国产3A大作，字体体系根植于中国传统书法美学，同时兼顾现代游戏的阅读效率。",
    fonts: [
      {
        name: "方正行楷 / FZ XingKai",
        role: "主标题字体",
        foundry: "方正字库",
        notes: "行楷字体介于行书与楷书之间，具有动感与神韵，与孙悟空的飞扬个性相互映衬。",
        cssFamily: "'Noto Serif SC', serif",
        sampleText: "踏上取经路",
      },
      {
        name: "思源宋体 / Source Han Serif",
        role: "剧情文本",
        foundry: "Adobe & Google",
        year: 2017,
        notes: "高度可读的泛中日韩宋体，在古典风格的剧情对白与物品说明中营造古籍质感。",
        cssFamily: "'Noto Serif SC', serif",
        sampleText: "天命人，大圣遗蜕",
      },
    ],
  },
  {
    id: 9,
    title: "星露谷物语",
    titleEn: "Stardew Valley",
    category: "game",
    genres: ["模拟经营", "农场", "休闲"],
    year: 2016,
    developer: "ConcernedApe",
    image: "https://images.unsplash.com/photo-1776286287707-32c03b3691da?w=600&h=800&fit=crop&auto=format",
    imageAlt: "水彩花园台阶",
    accentColor: "#7ec850",
    description: "一人开发的像素农场游戏，字体选择服务于温馨治愈的氛围，优先考虑屏幕像素级的可读性。",
    fonts: [
      {
        name: "Stardew Valley Font (自制)",
        role: "游戏全局字体",
        foundry: "ConcernedApe 自制",
        year: 2016,
        notes: "开发者 Eric Barone 专为游戏定制的像素点阵字体，确保在低分辨率像素风格下的完美显示。",
        cssFamily: "'Press Start 2P', cursive",
        googleFont: "https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap",
        sampleText: "Today is Spring 1, Year 1",
      },
      {
        name: "Fredoka One",
        role: "周边及宣传材料",
        foundry: "Google Fonts",
        year: 2010,
        notes: "圆润亲切的无衬线字体出现在游戏宣传材料中，强化了治愈系品牌调性。",
        cssFamily: "'Fredoka One', cursive",
        googleFont: "https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap",
        sampleText: "Stardew Valley",
      },
    ],
  },
  {
    id: 10,
    title: "博德之门 3",
    titleEn: "Baldur's Gate 3",
    category: "game",
    genres: ["角色扮演", "回合制", "奇幻"],
    year: 2023,
    developer: "Larian Studios",
    image: "https://images.unsplash.com/photo-1700531292661-65aa608c87c4?w=600&h=800&fit=crop&auto=format",
    imageAlt: "龙雕像建筑顶",
    accentColor: "#9b4dca",
    description: "D&D规则体系下的史诗奇幻RPG，字体方案需兼顾大量对话文本的阅读舒适度与高奇幻的视觉调性。",
    fonts: [
      {
        name: "Morpheus",
        role: "主标题字体",
        foundry: "URW++",
        notes: "高奇幻风格的装饰性花体字，最早因《魔兽争霸》系列而广为人知，BG3沿用了这一传统。",
        cssFamily: "'UnifrakturMaguntia', cursive",
        googleFont: "https://fonts.googleapis.com/css2?family=UnifrakturMaguntia&display=swap",
        sampleText: "Baldur's Gate",
      },
      {
        name: "Palatino Linotype",
        role: "正文与对话字体",
        foundry: "Linotype",
        year: 1949,
        notes: "赫尔曼·察普夫设计的经典人文主义衬线字体，在长篇对话文本中提供出色的可读性。",
        cssFamily: "Palatino, 'Palatino Linotype', serif",
        sampleText: "You have a tadpole in your brain.",
      },
    ],
  },
  {
    id: 11,
    title: "攻壳机动队",
    titleEn: "Ghost in the Shell",
    category: "film",
    genres: ["科幻动画", "赛博朋克", "哲学"],
    year: 1995,
    developer: "押井守 / Production I.G",
    image: "https://images.unsplash.com/photo-1633643092028-b66187af7d47?w=600&h=800&fit=crop&auto=format",
    imageAlt: "白色机器人立于白色背景",
    accentColor: "#00d4ff",
    description: "定义了赛博朋克视觉语言的里程碑动画，片中城市字景与数字代码的字体处理影响了无数后续作品。",
    fonts: [
      {
        name: "DIN 1451",
        role: "城市标牌字体",
        foundry: "Linotype",
        year: 1931,
        notes: "德国工业标准字体，被广泛用于片中的街道标牌和系统界面，传达工业社会的冰冷精确感。",
        cssFamily: "'Rajdhani', sans-serif",
        sampleText: "SECTION 9 / 公安九課",
      },
      {
        name: "Helvetica Neue",
        role: "字幕与界面文本",
        foundry: "Linotype",
        year: 1983,
        notes: "国际版字幕及海报普遍采用Helvetica，其中性无表情感与影片对人类本质的冷静追问相互呼应。",
        cssFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
        sampleText: "What is a ghost?",
      },
    ],
  },
  {
    id: 12,
    title: "新世纪福音战士",
    titleEn: "Neon Genesis Evangelion",
    category: "film",
    genres: ["机甲动画", "心理", "末日"],
    year: 1995,
    developer: "庵野秀明 / GAINAX",
    image: "https://images.unsplash.com/photo-1590562177087-ca6af9bb82ea?w=600&h=800&fit=crop&auto=format",
    imageAlt: "灰色金属机器",
    accentColor: "#ff4500",
    description: "EVA在排版上大量使用警戒红字与Helvetica/Gothic系字体，形成独特的「NERV风格」，影响延续至今。",
    fonts: [
      {
        name: "Helvetica / ヘルベチカ",
        role: "NERV标牌与警告文本",
        foundry: "Linotype",
        year: 1957,
        notes: "NERV基地内的所有警告标牌、倒计时与任务简报均使用Helvetica，这成为整个系列的视觉标志。",
        cssFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
        sampleText: "NERV HEADQUARTERS",
      },
      {
        name: "Matisse EB / マティス",
        role: "片头标题字体",
        foundry: "Fontworks",
        year: 1993,
        notes: "片头「残酷な天使のテーゼ」所使用的经典日文字体，其独特的笔画风格已与EVA品牌深度绑定。",
        cssFamily: "'Noto Serif SC', serif",
        sampleText: "残酷な天使のテーゼ",
      },
    ],
  },
  {
    id: 13,
    title: "银翼杀手 2049",
    titleEn: "Blade Runner 2049",
    category: "film",
    genres: ["科幻", "赛博朋克", "新黑色电影"],
    year: 2017,
    developer: "Denis Villeneuve / 华纳兄弟",
    image: "https://images.unsplash.com/photo-1599060052009-24d6d0b0161c?w=600&h=800&fit=crop&auto=format",
    imageAlt: "雨夜霓虹街道人群",
    accentColor: "#ff8c00",
    description: "维伦纽瓦执导的续集在字体选择上向原作致敬，同时引入更为内敛的现代主义排版，强化荒芜末世的孤寂感。",
    fonts: [
      {
        name: "Eurostile Extended",
        role: "片头与字幕字体",
        foundry: "Linotype",
        year: 1962,
        notes: "方形扩展比例的几何字体，自1982年原版《银翼杀手》沿用至今，是系列不可分割的视觉DNA。",
        cssFamily: "'Orbitron', sans-serif",
        sampleText: "LOS ANGELES · 2049",
      },
      {
        name: "Trade Gothic Condensed",
        role: "片中城市标牌",
        foundry: "Linotype",
        year: 1948,
        notes: "片中城市景观中的广告牌与指示标牌大量使用了这款收窄版的经典格罗特斯克字体。",
        cssFamily: "'Barlow Condensed', sans-serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;700&display=swap",
        sampleText: "WALLACE CORPORATION",
      },
    ],
  },
  {
    id: 14,
    title: "进击的巨人",
    titleEn: "Attack on Titan",
    category: "film",
    genres: ["动作动画", "奇幻", "黑暗"],
    year: 2013,
    developer: "谏山创 / MAPPA",
    image: "https://images.unsplash.com/photo-1672526521487-6b81b9569d6a?w=600&h=800&fit=crop&auto=format",
    imageAlt: "雾天废弃建筑",
    accentColor: "#8b1a1a",
    description: "动画版字体设计随着故事的世界观揭示而演变，从蒸汽朋克军事风格逐渐向更为写实的历史字体风格转变。",
    fonts: [
      {
        name: "Trajan Pro",
        role: "英文版标题字体",
        foundry: "Adobe",
        year: 1989,
        notes: "基于罗马柱碑铭文的大写字体，在英语版营销材料中广泛使用，传达历史叙事的厚重感。",
        cssFamily: "'Cinzel', serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Cinzel:wght@700&display=swap",
        sampleText: "ATTACK ON TITAN",
      },
      {
        name: "A-OTF 見出しゴMB31",
        role: "日文版标题字体",
        foundry: "Morisawa",
        notes: "日版宣传物料使用的粗体黑体字，张力十足的笔画与巨人主题的压迫感相得益彰。",
        cssFamily: "'Noto Sans SC', sans-serif",
        sampleText: "進撃の巨人",
      },
    ],
  },
  {
    id: 15,
    title: "鬼灭之刃",
    titleEn: "Demon Slayer: Kimetsu no Yaiba",
    category: "film",
    genres: ["动作动画", "大正时代", "历史"],
    year: 2019,
    developer: "吾峠呼世晴 / ufotable",
    image: "https://images.unsplash.com/photo-1740508905577-5fb7fea583df?w=600&h=800&fit=crop&auto=format",
    imageAlt: "抽象深色绘画",
    accentColor: "#e84545",
    description: "大正时代背景为字体选择提供了明确的历史坐标，和风木版印刷风格贯穿了整套视觉系统。",
    fonts: [
      {
        name: "A-OTF 解ミン / Kai Mincho",
        role: "日文标题与标志字体",
        foundry: "Morisawa",
        notes: "楷书体明朝字体兼具毛笔书法的流动感与活版印刷的规整度，完美还原大正时代的印刷美学。",
        cssFamily: "'Noto Serif SC', serif",
        sampleText: "鬼滅の刃",
      },
      {
        name: "Rokkitt",
        role: "英文版字幕",
        foundry: "Google Fonts",
        year: 2011,
        notes: "英语字幕采用衬线字体配合传统排版节奏，在保持西方观众阅读舒适度的同时呼应原作的历史气质。",
        cssFamily: "'Rokkitt', serif",
        googleFont: "https://fonts.googleapis.com/css2?family=Rokkitt:wght@400;600&display=swap",
        sampleText: "Total Concentration Breathing",
      },
    ],
  },
  {
    id: 16,
    title: "蜘蛛侠：平行宇宙",
    titleEn: "Spider-Man: Into the Spider-Verse",
    category: "film",
    genres: ["动画", "超级英雄", "漫画风"],
    year: 2018,
    developer: "Sony Pictures Animation",
    image: "https://images.unsplash.com/photo-1674506205105-1784168e8d19?w=600&h=800&fit=crop&auto=format",
    imageAlt: "紫色树木山景",
    accentColor: "#ff2d9f",
    description: "革命性的漫画格视觉风格，字体排版本身就是叙事工具——漫辑字体、印刷网点与对话框共同构成独特的视觉语法。",
    fonts: [
      {
        name: "Bangers",
        role: "动作音效文字",
        foundry: "Google Fonts / Vernon Adams",
        year: 2010,
        notes: "典型的漫画音效字体，用于表现POW、BAM等动作音效，完全契合影片的漫画格美学。",
        cssFamily: "'Bangers', cursive",
        googleFont: "https://fonts.googleapis.com/css2?family=Bangers&display=swap",
        sampleText: "THWIP! KA-POW!",
      },
      {
        name: "CC Wild Words",
        role: "对话泡文字",
        foundry: "Comicraft",
        year: 2000,
        notes: "专业漫画对话字体，流畅的手写风格与漫画对话框完美结合，是美漫字体的行业标准之一。",
        cssFamily: "'Fredoka One', cursive",
        sampleText: "Anyone can wear the mask.",
      },
    ],
  },
  {
    id: 17,
    title: "星球大战",
    titleEn: "Star Wars",
    category: "film",
    genres: ["科幻", "太空歌剧", "史诗"],
    year: 1977,
    developer: "George Lucas / 卢卡斯影业",
    image: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=600&h=800&fit=crop&auto=format",
    imageAlt: "星空剪影人物",
    accentColor: "#ffe81f",
    description: "汉字「星球大战」的字体选择与开场爬字幕已成为流行文化的集体记忆，构成了电影史上最具辨识度的排版之一。",
    fonts: [
      {
        name: "Univers 65 Bold Oblique",
        role: "开场爬字幕",
        foundry: "Linotype / Adrian Frutiger",
        year: 1957,
        notes: "标志性的开场黄字滚动字幕使用倾斜的Univers字体，这一选择已与星球大战品牌永久绑定。",
        cssFamily: "'Rajdhani', sans-serif",
        sampleText: "A long time ago in a galaxy far, far away....",
      },
      {
        name: "ITC Serif Gothic",
        role: "首部曲标题字体",
        foundry: "ITC",
        year: 1972,
        notes: "原版1977年电影标题所用字体，圆润的几何衬线形式融合了科幻与复古感，为系列奠定了视觉基调。",
        cssFamily: "'Fredoka One', cursive",
        sampleText: "STAR WARS",
      },
    ],
  },
  {
    id: 18,
    title: "魔法少女小圆",
    titleEn: "Puella Magi Madoka Magica",
    category: "film",
    genres: ["魔法少女", "心理", "解构"],
    year: 2011,
    developer: "虚渊玄 / SHAFT",
    image: "https://images.unsplash.com/photo-1715947182183-364b497043c1?w=600&h=800&fit=crop&auto=format",
    imageAlt: "田野树丛风景",
    accentColor: "#ff69b4",
    description: "SHAFT的极简派标题排版与魔女界的「德语拼贴字体」形成强烈对比，构成了叙事上的视觉双重性。",
    fonts: [
      {
        name: "Alte Schwabacher",
        role: "魔女界文字",
        foundry: "传统黑体字",
        notes: "魔女界的德语铭文使用中世纪黑体字（Blackletter），在可爱的外表下埋下黑暗叙事伏笔。",
        cssFamily: "'UnifrakturMaguntia', cursive",
        googleFont: "https://fonts.googleapis.com/css2?family=UnifrakturMaguntia&display=swap",
        sampleText: "Du musst Mahou Shoujo werden",
      },
      {
        name: "ヒラギノ角ゴ / Hiragino Kaku Gothic",
        role: "片头标题字体",
        foundry: "字游工房",
        year: 1999,
        notes: "SHAFT极简派片头大量留白，配合苹果系统内建字体Hiragino的纤细字重，制造出冷峻的视觉张力。",
        cssFamily: "'Noto Sans SC', sans-serif",
        sampleText: "魔法少女まどか☆マギカ",
      },
    ],
  },
  {
    id: 19,
    title: "命运石之门",
    titleEn: "Steins;Gate",
    category: "film",
    genres: ["科幻动画", "时间旅行", "视觉小说"],
    year: 2011,
    developer: "5pb. / Nitroplus / White Fox",
    image: "https://images.unsplash.com/photo-1535391879778-3bae11d29a24?w=600&h=800&fit=crop&auto=format",
    imageAlt: "夜景高楼群",
    accentColor: "#d4721a",
    description: "视觉小说改编动画保留了原作大量的终端界面与手机短信文字，字体设计服务于「现实系科幻」的沉浸体验。",
    fonts: [
      {
        name: "VT323",
        role: "终端界面字体",
        foundry: "Google Fonts",
        year: 2014,
        notes: "Okabe实验室的旧式CRT终端显示器大量使用点阵终端风格字体，强化了老旧机器的质感。",
        cssFamily: "'VT323', monospace",
        googleFont: "https://fonts.googleapis.com/css2?family=VT323&display=swap",
        sampleText: "EL PSY KONGROO",
      },
      {
        name: "源ノ角ゴシック / Source Han Sans",
        role: "字幕与UI字体",
        foundry: "Adobe & Google",
        year: 2014,
        notes: "现代感十足的泛中日韩黑体，用于字幕系统，在密集信息中保持出色的层次感与可读性。",
        cssFamily: "'Noto Sans SC', sans-serif",
        sampleText: "世界線変動率：0.000001%",
      },
    ],
  },
  {
    id: 20,
    title: "空洞骑士",
    titleEn: "Hollow Knight",
    category: "game",
    genres: ["银河恶魔城", "平台动作", "独立"],
    year: 2017,
    developer: "Team Cherry",
    image: "https://images.unsplash.com/photo-1635161594526-238c750e0252?w=600&h=800&fit=crop&auto=format",
    imageAlt: "雾中森林灯塔",
    accentColor: "#a259ff",
    description: "手绘风格的昆虫世界中，字体系统延续了手工感，自制字体与手绘界面元素融为一体。",
    fonts: [
      {
        name: "Hollow Knight (自制)",
        role: "游戏全局字体",
        foundry: "Team Cherry 自制",
        year: 2017,
        notes: "开发团队专门定制了带有昆虫触感的手写风格字体，斑驳的笔画呼应了虫族文明的古老与衰落。",
        cssFamily: "'IM Fell English', serif",
        googleFont: "https://fonts.googleapis.com/css2?family=IM+Fell+English:ital@0;1&display=swap",
        sampleText: "Once, this kingdom was pure.",
      },
    ],
  },
]

// Inject Google Fonts
const injectedFonts = new Set<string>()
export function injectFont(url: string) {
  if (injectedFonts.has(url)) return
  injectedFonts.add(url)
  const link = document.createElement("link")
  link.rel = "stylesheet"
  link.href = url
  document.head.appendChild(link)
}

WORKS.forEach((w) => w.fonts.forEach((f) => { if (f.googleFont) injectFont(f.googleFont) }))
